const dunmerFemaleNames = [
    "Aduri Serethi",
    "Alavesa Areloth",
    "Almion Arenim",
    "Anareren",
    "Anes Vendu",
    "Anuriel",
    "Aphril",
    "Arara Uvulas",
    "Arelyna",
    "Arlene Maren",
    "Ashalki",
    "Ashana Llarys",
    "Assenarie Llatto",
    "Assintash",
    "Assirari",
    "Atahban Assirari",
    "Athanas",
    "Athril",
    "Avrusa Sarethi",
    "Bendu Olo",
    "Brelas",
    "Brelas Othren",
    "Briring",
    "Briring Dael",
    "Brolmir",
    "Caryarel",
    "Ciranya",
    "Dravynea the Stoneweaver",
    "Dreyla Alor",
    "Drilame Serethi",
    "Drusus",
    "Drusus Maximus",
    "Dryn",
    "Duneri Serethi",
    "Eldra",
    "Eldrilu Dalen",
    "Eldrya",
    "Elone",
    "Endris Serethi",
    "Eno Hlaalu",
    "Eno Romari",
    "Erithrandil",
    "Esdrufus",
    "Esdrufus Othril",
    "Esma",
    "Esra",
    "Estinan",
    "Estulmir",
    "Estus Dael",
    "Ettiene",
    "Falen Andrethi",
    "Faralda",
    "Felen Relas",
    "Feldrasa",
    "Felis Sarandas",
    "Felisi Serethi",
    "Fervyn",
    "Fevyn Ralen",
    "Folvys Alen",
    "Folvys Andalor",
    "Folvys Hleran",
    "Galbedir",
    "Gami",
    "Gathal Llervu",
    "Gathal Nemal",
    "Gayran",
    "Gils Drelas",
    "Girvu Darethi",
    "Girynu Darethi",
    "Golven Venim",
    "Gorvas Vules",
    "Gulitte",
    "Gulitte Bienne",
    "Gurak",
    "Gurak gro-Bagrat",
    "Guril Retheran",
    "Gurise Hleran",
    "Gurise Serethi",
    "Hadar",
    "Hadrin",
    "Hanin",
    "Hannabi",
    "Hannabi Zabynatus",
    "Helende",
    "Helseth Hlaalu",
    "Hlana Darethi",
    "Idela Mari",
    "Idela Othren",
    "Idrenie Nerothren",
    "Idrolothi",
    "Ildari Sarothril",
    "Ildene",
    "Ildene Nerothren",
    "Ildram",
    "Ildrasa Othren",
    "Ildri Sarothril",
    "Ildrya",
    "Ildrya Dalvilu",
    "Illdi",
    "Ilmeni Arelas",
    "Ilmeni Dren",
    "Ilmeni Farothran",
    "Ilmeni Morvayn",
    "Ilmeni Raram",
    "Ilmeni Rothalen",
    "Ilmeni Tharam",
    "Ilmeni's House",
    "Ilmeni's Room",
    "Ilver Aralas",
    "Ilver Indarys",
    "Indrele Rathryon",
    "Irna",
    "Irranhu",
    "Irval Lerus",
    "Irvama Othelas",
    "Irvama Othrelas",
    "Irvona Maren",
    "Isadati",
    "Issayar"
];

module.exports = { dunmerFemaleNames }